### ISSUE TITLE
Problem of code

### ISSUE THREAD

**Issue by xuyin218** [iQua/flsim#1]
Hello! I'm sorry to bother you. In your paper, you said that you need use the PCA to achieve Dimension Reduction, but I cannot find in your codes. Could you tell me where is this part in your codes? Thank you very much!

**Comment by kaplanz** [comment]
I've uploaded our PCA scripts. I hope that helps!

**Comment by yangzhaogit** [comment]
Hello ! May I ask about the dqn part? It seems it has been removed. May I see this part of code ? Thank you.

**Comment by caozhangyingfei** [comment]
> 你好！很抱歉打扰你了在您的论文中，您说您需要使用 PCA 来实现尺寸缩小，但我无法在您的代码中找到。你能告诉我这部分在你的代码

> Hello! I'm sorry to bother you. In your paper, you said that you need use the PCA to achieve Dimension Reduction, but I cannot find in your codes. Could you tell me where is this part in your codes? Thank you very much!

hello！Do you have  the dqn part ? May I have a see?  Thank you very much!

**Comment by xuyin218** [comment]
sorry，i do not have. i have given up, because it is so difficult....------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;guoenwei&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月7日(星期天) 下午2:23
收件人:&nbsp;&quot;iQua/flsim&quot;<flsim@noreply.github.com&gt;;
抄送:&nbsp;&quot;xuyin218&quot;<1272261379@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iQua/flsim] Problem of code (#1)

**Comment by caozhangyingfei** [comment]
Hello! I'm sorry to botter you. I'm interested in you work! May I have a see the code about dqn. Thank you very much!

**Comment by tian1327** [comment]
> Hello! I'm sorry to botter you. I'm interested in you work! May I have a see the code about dqn. Thank you very much!

Hello, just wondering if you have the DQN code pls
